POS Update
zap-me/premio_stage pull request #11
Opened 2021-06-17 03:10 UTC by 4855062503

2021-06-18 03:21 UTC, djpnewton requested changes

2021-06-18 03:21 UTC, djpnewton commented on test_pos/app.html
> +      <style>
I think it would be nicer to move this into a seperate css file

2021-06-18 03:21 UTC, djpnewton commented on test_pos/app.html
> -    const apikey = 'XXXXX';
read from localStorage, also have a button to update what is in localStorage

2021-06-18 03:21 UTC, djpnewton commented on test_pos/app.html
> +              //TODO if photoType =- 'svg'
handle the case of SVG

2021-06-18 03:21 UTC, djpnewton commented on test_pos/app.html
> +
fix up weird spacing here

2021-06-18 03:21 UTC, djpnewton commented on test_pos/app.html
> +                                console.log("sent");
you should validate the amount and invoice id, also show a nice popup to show the rebate succeeded

2021-06-18 03:21 UTC, djpnewton commented on test_pos/app.html
> +                              Swal.showValidationMessage('please enter an email');
have an option to scan qr code

2021-06-18 03:26 UTC, djpnewton commented
you should be developing from a feature branch, otherwise you will get fucked up when other commits get pushed to master

2021-07-12 04:29 UTC, djpnewton commented
the spacing of your JS is not consistent

2021-07-13 00:44 UTC, djpnewton commented
> the spacing of your JS is not consistent

@4855062503 can you address this

2021-07-13 21:24 UTC, 4855062503 commented
> > the spacing of your JS is not consistent
> 
> @4855062503 can you address this

Sure.

2021-07-27 04:12 UTC, closed without merging